### PR TITLE
Fix bug in loop over cluster nodes

### PR DESCRIPTION
**Pull request by vwmaus**
This fix worked me. I perform some extensive tests later today. Let me know if it works for you.

### CODE REVIEW

**Comment by vwmaus** [comment]
@rkstan I just tried it on the cluster now I get the same error. I will figure it out now and send a solution ASAP.

**Comment by rkstan** [comment]
@vwmaus yeah I still get the same error too. Thank you!!

**Comment by vwmaus** [comment]
@rkstan it works now. At least here :) See  #4

**Comment by rkstan** [comment]
@vwmaus it worked! Thank you so much. you are the best

**Comment by vwmaus** [comment]
@rkstan I am happy to help ;)

**Pull request merged**
